  version: "3.7"

  services:
    node:
        image: node:18
        working_dir: /usr/src/app
        tty: true
        volumes:
            - .:/usr/src/app
        ports:
        - "3000:3000"
        command: sh -c "npm install && npm run dev"